[package]
name = "rust-nes-emulator"
version = "0.1.0"
authors = ["K <kamiyaowl@gmail.com>"]
edition = "2018"

[features]
default = [ "unsafe-opt" ]
unsafe-opt = []

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true

[lib]
path = "src/lib.rs"
name = "rust_nes_emulator"

[dependencies]
log = "0.4"
env_logger = "0.9"
#bevy = { git = "https://github.com/bevyengine/bevy" }
egui = { path = "../egui/egui" }
egui_glow = { path = "../egui/egui_glow" }
glow = "0.11"
glutin = "0.27"
pretty_env_logger = { git = "https://github.com/project-anni/pretty-env-logger.git" }
image = "0.23"