[package]
name = "nes-emulator"
version = "0.1.0"
authors = ["Robert Bragg <robert@sixbynine.org>", "K <kamiyaowl@gmail.com>"]
edition = "2018"
resolver="2"

[features]
default = [ "unsafe-opt" ]
unsafe-opt = []
trace = []

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true

[lib]
path = "src/lib.rs"
#name = "rust_nes_emulator"

[[bin]]
path = "src/main.rs"
name = "nes_emulator"

[dependencies]
log = "0.4"
env_logger = "0.9"
winit = "0.26"
wgpu = "0.13"
pollster = "0.2"
egui = "0.18"
egui-wgpu = { version = "0.18", features = [ "winit" ] }
egui-winit = { version = "0.18", default-features = false }
bytemuck = "1.9"
bitflags = "1"
cpal = "0.13"
ring-channel = "0.11"
anyhow = "1"
pretty_env_logger = { git = "https://github.com/project-anni/pretty-env-logger.git" }
image = "0.23"
rfd = "0.8"
clap = { version = "3.2.6", features = ["derive", "cargo"] }


[patch.crates-io]
egui = { git = "https://github.com/emilk/egui" }
egui-wgpu = { git = "https://github.com/emilk/egui" }
egui-winit = { git = "https://github.com/emilk/egui" }
#egui_extras = { git = "https://github.com/emilk/egui" }
#egui = { path = "../../../egui/egui" }
#egui-wgpu = { path = "../../../egui/egui-wgpu" }
#egui-winit = { path = "../../../egui/egui-winit" }
