[package]
name = "nes-emulator"
version = "0.1.0"
authors = ["Robert Bragg <robert@sixbynine.org>", "K <kamiyaowl@gmail.com>"]
edition = "2018"

[features]
default = [ "unsafe-opt" ]
unsafe-opt = []
trace = []

[lib]
path = "src/lib.rs"
#name = "rust_nes_emulator"

[dependencies]
log = "0.4"
env_logger = "0.9"
bytemuck = "1.9"
bitflags = "1"
anyhow = "1"
image = "0.23"
